name: Update Google Trends Map

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo
      - name: Check out repo
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 4. Run the script
      - name: Run update script
        run: |
          python update_google_trends.py
      
      # 5. Commit & push changes (if index.html is updated)
      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add index.html
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update index.html [skip ci]"
            git push
          fi
